<a href="https://colab.research.google.com/github/bhagyasree2004/MachineLearning_Module/blob/main/CLASSIFICATION_MODELS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Contract'] = le.fit_transform(df['Contract'])

In [ ]:
df.TotalCharges=pd.to_numeric(df.TotalCharges,errors='coerce')


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   int64  
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
df.dropna(how='any',inplace=True)

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,0,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,1,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,0,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,1,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes


In [ ]:
df['Churn'].value_counts()/len(df)*100

,count
Churn,
No,73.421502
Yes,26.578498


In [ ]:
x=df.drop(["customerID","Churn"],axis=1)

In [ ]:

x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,0,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,1,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,0,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,1,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,0,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,1,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,1,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,0,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,0,Yes,Mailed check,74.40,306.60


In [ ]:
y=df.Churn.values

In [ ]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [ ]:
print(x.columns)

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')


In [ ]:
#convert categorical column into numewrical features

x = pd.get_dummies(
    x,
    columns=[
        'gender', 'Partner', 'Dependents', 'PhoneService',
        'MultipleLines', 'InternetService', 'OnlineSecurity',
        'OnlineBackup', 'DeviceProtection', 'TechSupport',
        'StreamingTV', 'StreamingMovies', 'Contract',
        'PaperlessBilling', 'PaymentMethod'
    ],
    drop_first=True
)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
len(x_train)

5274

In [ ]:
len(x_test)

1758

In [ ]:
#feature scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [ ]:
x_train

array([[-0.43679284,  1.62814876,  1.46066229, ..., -0.52513044,
        -0.72011932, -0.54301809],
       [-0.43679284,  1.46485552, -1.4956825 , ..., -0.52513044,
        -0.72011932, -0.54301809],
       [-0.43679284, -0.86207312,  0.81239954, ..., -0.52513044,
         1.38865875, -0.54301809],
       ...,
       [-0.43679284,  0.73003595,  1.37067209, ...,  1.90428879,
        -0.72011932, -0.54301809],
       [-0.43679284, -0.73960319,  0.52076462, ...,  1.90428879,
        -0.72011932, -0.54301809],
       [-0.43679284,  1.30156228,  1.32734347, ...,  1.90428879,
        -0.72011932, -0.54301809]])

In [ ]:
x_test

array([[-0.43679284, -1.27030621, -1.4723517 , ..., -0.52513044,
         1.38865875, -0.54301809],
       [-0.43679284, -0.65795657, -1.47401819, ...,  1.90428879,
        -0.72011932, -0.54301809],
       [-0.43679284, -1.27030621, -1.50068195, ...,  1.90428879,
        -0.72011932, -0.54301809],
       ...,
       [-0.43679284, -1.27030621, -0.34914066, ..., -0.52513044,
         1.38865875, -0.54301809],
       [ 2.2894148 ,  0.89332919,  0.01415312, ..., -0.52513044,
        -0.72011932, -0.54301809],
       [-0.43679284,  0.81168257, -1.49901547, ..., -0.52513044,
        -0.72011932,  1.84155927]])

In [ ]:
# KNN
#call the knn classifier
from sklearn.neighbors import KNeighborsClassifier

#initiating the classifier
model=KNeighborsClassifier()

#passing the data
model.fit(x_train,y_train)


KNeighborsClassifier()

In [ ]:
#predictions
y_pred=model.predict(x_test)


In [ ]:
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
y_test

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix =to check the model is behaving /accuracy

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1117,  194],
       [ 226,  221]])

In [ ]:
#accuracy score
accuracy_score(y_test,y_pred)


0.7610921501706485

In [ ]:
#accurcay score
accuracy_score(y_test,y_pred)*100

76.10921501706484

In [ ]:
#new data prediction

x_test[0]

array([-0.43679284, -1.27030621, -1.4723517 , -0.993177  ,  0.9943278 ,
       -0.96313632, -0.65370807,  0.32860796, -0.32860796, -0.8562465 ,
       -0.88860371,  1.90749113,  1.90749113, -0.63044134,  1.90749113,
       -0.72376587,  1.90749113, -0.71981575,  1.90749113, -0.63337901,
        1.90749113, -0.79327573,  1.90749113, -0.80314416, -0.51335775,
       -0.55500965, -1.21828586, -0.52513044,  1.38865875, -0.54301809])

In [ ]:
data=[[0,2,87,178,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,2,1,0,0,1,2,3]]


In [ ]:
data_sc=sc.transform(data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
single=model.predict(data_sc)
print(single)

['No']


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred


array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
y_test

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1066,  245],
       [ 231,  216]])

In [ ]:
#ACCURACY SCORE

accuracy_score(y_test,y_pred)*100

72.92377701934016

In [ ]:
#entropy and gini index
#entropy used for classification -to find uncertianity

#gini index to find mixed data


In [ ]:
#random forest
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
# confusion tree
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1185,  126],
       [ 237,  210]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

79.35153583617748

In [ ]:
#SVM
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1202,  109],
       [ 230,  217]])

In [ ]:
#accuracy score
accuracy_score(y_test,y_pred)*100

80.71672354948805

In [ ]:
#ensemble learning-boosting
#gradient boosting
#extreme gradient boosting(XG Boost)
#Ada boost
#Catboost


In [ ]:
#call the AdaBoost Clasifier
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier(n_estimators=100)
model.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1191,  120],
       [ 226,  221]])

In [ ]:
#accuracy score
accuracy_score(y_test,y_pred)*100

80.31854379977247

In [ ]:
#CatBoost
!pip install catboost


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.4 MB/s eta 0:00:00


In [ ]:
#catboost
from catboost import CatBoostClassifier
model=CatBoostClassifier()
model.fit(x_train,y_train)


Learning rate set to 0.020955
0:	learn: 0.6794606	total: 52.9ms	remaining: 52.9s
1:	learn: 0.6675218	total: 58.1ms	remaining: 29s
2:	learn: 0.6552688	total: 64ms	remaining: 21.3s
3:	learn: 0.6434315	total: 71.4ms	remaining: 17.8s
4:	learn: 0.6324935	total: 77.5ms	remaining: 15.4s
5:	learn: 0.6221416	total: 84.1ms	remaining: 13.9s
6:	learn: 0.6112441	total: 89.7ms	remaining: 12.7s
7:	learn: 0.6006928	total: 96.1ms	remaining: 11.9s
8:	learn: 0.5905683	total: 102ms	remaining: 11.2s
9:	learn: 0.5834001	total: 108ms	remaining: 10.7s
10:	learn: 0.5749857	total: 114ms	remaining: 10.2s
11:	learn: 0.5676071	total: 120ms	remaining: 9.85s
12:	learn: 0.5600802	total: 124ms	remaining: 9.43s
13:	learn: 0.5533950	total: 129ms	remaining: 9.08s
14:	learn: 0.5472480	total: 134ms	remaining: 8.79s
15:	learn: 0.5410152	total: 139ms	remaining: 8.53s
16:	learn: 0.5354258	total: 144ms	remaining: 8.3s
17:	learn: 0.5298523	total: 148ms	remaining: 8.09s
18:	learn: 0.5246564	total: 156ms	remaining: 8.04s
19:	lear

CatBoostClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1180,  131],
       [ 224,  223]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

79.806598407281

In [ ]:
#Gradient boosting
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier()
model.fit(x_train,y_train)

GradientBoostingClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1194,  117],
       [ 218,  229]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

80.94425483503981

In [ ]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

model=XGBClassifier()

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1165,  146],
       [ 211,  236]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

79.69283276450511

In [ ]:
#upto here classification models completed

In [ ]:
#Regression Models

import pandas as pd
